# Generated by Django 5.1.5 on 2025-02-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0003_employe_employe_emp_email_7254bc_idx_and_more'),
        ('typeconge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de Début')),
                ('end_date', models.DateField(verbose_name='Date de Fin')),
                ('status', models.CharField(choices=[('en cours', 'En Cours'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='employe.employe', verbose_name='Employé')),
                ('typeconge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='typeconge.typeconge', verbose_name='Type de Congé')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['start_date'],
            },
        ),
    ]
