# Generated by Django 5.1.5 on 2025-02-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0002_alter_employe_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('conge payé', 'Congé Payé'), ('conge sans solde', 'Congé Sans Solde'), ('conge maladie', 'Congé Maladie'), ('conge maternité', 'Congé Maternité'), ('conge paternité', 'Congé Paternité'), ('conge exceptionnel', 'Congé Exceptionnel'), ('conge annuel', 'Congé Annuel')], max_length=50, verbose_name='Type de Congé')),
                ('start_date', models.DateField(verbose_name='Date de Début')),
                ('end_date', models.DateField(verbose_name='Date de Fin')),
                ('status', models.CharField(choices=[('en cours', 'En Cours'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='employe.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['start_date'],
            },
        ),
    ]
