# Generated by Django 5.1.5 on 2025-02-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'ordering': ['startDate'], 'verbose_name': 'Congé', 'verbose_name_plural': 'Congés'},
        ),
        migrations.RenameField(
            model_name='conge',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='conge',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
