# Generated by Django 5.1.5 on 2025-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('conge paye', 'Congé Payé'), ('conge sans solde', 'Congé Sans Solde'), ('conge maladie', 'Congé Maladie'), ('conge maternite', 'Congé Maternité'), ('conge paternite', 'Congé Paternité'), ('conge exceptionnel', 'Congé Exceptionnel'), ('conge annuel', 'Congé Annuel')], max_length=50, verbose_name='Type de Congé'),
        ),
    ]
