# Generated by Django 5.1.5 on 2025-02-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0002_alter_conge_type_conge'),
        ('typeconge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conges', to='typeconge.typeconge', verbose_name='Type de Congé'),
        ),
    ]
