# Generated by Django 4.1.3 on 2023-03-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_useraccount_auth_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='type',
            new_name='role',
        ),
    ]
