# Generated by Django 4.1.3 on 2023-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('HR', 'HR'), ('employee', 'employee')], default='admin', max_length=8),
        ),
    ]
