# Generated by Django 4.1.3 on 2023-03-21 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_useraccount_first_name_useraccount_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('useraccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.useraccount',),
        ),
    ]
