# Generated by Django 4.1.3 on 2023-04-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_employee_address_employee_cin_employee_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='family_situation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender_user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='rib',
        ),
    ]
