# Generated by Django 4.1.3 on 2023-10-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_useraccount_gender_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='departement',
            new_name='department',
        ),
    ]
