version: "3.9"
services:
  db:
    image: postgres:16.1-alpine3.18
    restart: always
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~