# Generated by Django 5.1.5 on 2025-02-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0003_employe_employe_emp_email_7254bc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('traité', 'Traité'), ('en attente', 'En attente')], default='en attente', max_length=10)),
                ('employe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='employe.employe')),
            ],
        ),
    ]
