# Generated by Django 5.1.5 on 2025-03-07 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_employe_cnss_employe_salaire_base'),
        ('salaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaire',
            name='employe_id',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='month',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='status',
        ),
        migrations.AddField(
            model_name='salaire',
            name='acompte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Acompte'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='apoint',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Apoint'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='cnss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='CNSS'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='conge_paye',
            field=models.IntegerField(default=0, verbose_name='Congés payés'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='css',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='CSS'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='employe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='employe.employe', verbose_name='Employé'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaire',
            name='heures_sup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Heures supplémentaires'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='impots',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Impôts'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='jour_ferie',
            field=models.IntegerField(default=0, verbose_name='Jours fériés'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='jour_heure_travaille',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Jour/Heure travaillé'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='mode_paiement',
            field=models.CharField(choices=[('virement bancaire', 'Virement Bancaire'), ('cheque', 'Cheque'), ('especes', 'Especes')], default='virement bancaire', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='prime_presence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prime de présence'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='prime_transport',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prime de transport'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='prix_conge_paye',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix congé payé'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='prix_jour_ferie',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix jour férié'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='prix_tot_conge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix total des conges payés'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='prix_tot_ferie',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix total des jours férié'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='prix_tot_sup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix total des heures sup'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Salaire'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaire',
            name='salaire_base',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15, verbose_name='Salaire de Base'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaire',
            name='salaire_brut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salaire brut'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='salaire_imposable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salaire imposable'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='salaire_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire net'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='taux_heure_sup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux horaire des heures sup'),
        ),
    ]
