# Generated by Django 5.1.5 on 2025-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0002_remove_salaire_employe_id_remove_salaire_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='jour_abcense',
            field=models.IntegerField(default=0, verbose_name="Jours d'absence"),
        ),
    ]
