# Generated by Django 5.1.5 on 2025-03-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0004_salaire_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaire',
            old_name='employe',
            new_name='employe_mat',
        ),
        migrations.AddField(
            model_name='salaire',
            name='employe_nom',
            field=models.CharField(default=1, editable=False, max_length=100, verbose_name="Nom de l'employé"),
            preserve_default=False,
        ),
    ]
