# Generated by Django 5.1.5 on 2025-03-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0005_rename_employe_salaire_employe_mat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaire',
            old_name='employe_mat',
            new_name='employe',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='employe_nom',
        ),
    ]
