# Generated by Django 5.1.5 on 2025-03-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0006_rename_employe_mat_salaire_employe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaire',
            name='apoint',
        ),
        migrations.AddField(
            model_name='salaire',
            name='appointmoins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Apoint -'),
        ),
        migrations.AddField(
            model_name='salaire',
            name='appointplus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Apoint +'),
        ),
    ]
