# Generated by Django 5.1.6 on 2025-02-07 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='departement.departement'),
        ),
    ]
