# Generated by Django 5.1.5 on 2025-02-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0002_alter_employe_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee', models.TimeField()),
                ('pause_debut', models.TimeField()),
                ('pause_fin', models.TimeField()),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='employe.employe', verbose_name='Employe')),
            ],
        ),
    ]
