# Generated by Django 4.1.3 on 2023-03-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_employee_alter_useraccount_email_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
