# Generated by Django 4.1.3 on 2023-03-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_type_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('HR', 'HR'), ('EMPLOYEE', 'Employee')], default='ADMIN', max_length=8),
        ),
    ]
