# Generated by Django 4.1.3 on 2023-05-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_useraccount_address_useraccount_cin_useraccount_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='matricule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
