# Generated by Django 4.1.3 on 2023-05-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_useraccount_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['id']},
        ),
    ]
