# Generated by Django 4.1.3 on 2023-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_useraccount_is_deleted_alter_useraccount_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='gender_user',
            field=models.CharField(blank=True, choices=[('Homme', 'homme'), ('Femme', 'femme')], default='homme', max_length=200, null=True),
        ),
    ]
