# Generated by Django 4.1.3 on 2023-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_configurationdays_break_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationdays',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='configurationdays',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
