# Generated by Django 4.1.3 on 2023-04-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_overlapperiod_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlapperiod',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('Holiday schedule', 'Holiday schedule'), ('Flexible schedule', 'Flexible schedule'), ('Fixed schedule', 'Fixed schedule')], max_length=100, null=True),
        ),
    ]
