# Generated by Django 4.1.3 on 2023-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_alter_overlapperiod_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationdays',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
