# Generated by Django 4.1.3 on 2023-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_alter_configurationdays_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationdays',
            name='duration',
            field=models.TimeField(blank=True, max_length=255, null=True),
        ),
    ]
