# Generated by Django 4.1.3 on 2023-09-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_remove_overlapperiod_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlapPeriodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='overlapperiod',
            old_name='departement',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='overlapperiod',
            name='schedule_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.overlapperiodtype'),
        ),
    ]
