# Generated by Django 4.1.3 on 2023-10-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0024_dayschedule_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='dayschedule',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='weeklyschedule',
            options={'ordering': ['id']},
        ),
    ]
