# Generated by Django 5.1.5 on 2025-02-28 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0004_employe_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.PositiveIntegerField(blank=True, null=True, verbose_name='UID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='employe.employe', verbose_name='Employe')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'unique_together': {('employe',)},
            },
        ),
        migrations.CreateModel(
            name='LabelData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('startPause', models.DateTimeField()),
                ('endPause', models.DateTimeField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='label.label')),
            ],
        ),
    ]
