# Generated by Django 5.1.5 on 2025-02-20 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0003_employe_employe_emp_email_7254bc_idx_and_more'),
        ('service', '0002_alter_service_options_alter_service_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='employe.employe')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='service.service')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='LabelData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('occupancy', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bg_color', models.CharField(max_length=20)),
                ('start_pause', models.DateTimeField()),
                ('end_pause', models.DateTimeField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='label.label')),
            ],
        ),
    ]
