# Generated by Django 5.1.5 on 2025-02-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeldata',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('en pause', 'En Pause'), ('en conge', 'En Congé'), ('absent', 'Absent'), ('fin de service', 'Fin de Service'), ('anomalie', 'Anomalie'), ('jour ferie', 'Jour Férié')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
