# Generated by Django 5.1.5 on 2025-02-20 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_employe_employe_emp_email_7254bc_idx_and_more'),
        ('label', '0001_initial'),
        ('service', '0002_alter_service_options_alter_service_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='employe.employe', verbose_name='Employe'),
        ),
        migrations.AlterField(
            model_name='label',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labels', to='service.service', verbose_name='Service'),
        ),
    ]
