# Generated by Django 5.1.5 on 2025-02-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_alter_label_employee_alter_label_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='employee',
            new_name='employe',
        ),
    ]
