# Generated by Django 5.1.5 on 2025-02-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_labeldata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='uid',
        ),
    ]
