# Generated by Django 5.1.5 on 2025-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_remove_label_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='uid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='UID'),
        ),
    ]
