# Generated by Django 5.1.5 on 2025-02-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_employe_employe_emp_email_7254bc_idx_and_more'),
        ('label', '0003_rename_employee_label_employe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('employe',)},
        ),
    ]
