# Generated by Django 5.1.5 on 2025-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_label_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldata',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('en pause', 'En Pause'), ('en conge', 'En Congé'), ('absent', 'Absent'), ('fin de service', 'Fin de Service'), ('anomalie', 'Anomalie'), ('jour ferie', 'Jour Férié')], max_length=30),
        ),
    ]
