# Generated by Django 5.1.5 on 2025-02-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_alter_label_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeldata',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='labeldata',
            old_name='end_pause',
            new_name='endPause',
        ),
        migrations.RenameField(
            model_name='labeldata',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='labeldata',
            old_name='start_pause',
            new_name='startPause',
        ),
    ]
