# Generated by Django 5.1.5 on 2025-02-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_rename_end_date_labeldata_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeldata',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='labeldata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='labeldata',
            name='occupancy',
        ),
        migrations.RemoveField(
            model_name='labeldata',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='labeldata',
            name='title',
        ),
        migrations.AddField(
            model_name='labeldata',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('en pause', 'En Pause'), ('en conge', 'En Congé'), ('absent', 'Absent'), ('fin de service', 'Fin de Service'), ('anomalie', 'Anomalie'), ('jour ferie', 'Jour Férié')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
