# Generated by Django 5.1.5 on 2025-02-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_rename_end_date_labeldata_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='zkteco_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ZKTeco ID'),
        ),
    ]
