# Generated by Django 5.1.5 on 2025-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0005_alter_labeldata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldata',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labeldata',
            name='endPause',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labeldata',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labeldata',
            name='startPause',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
