# Generated by Django 5.1.5 on 2025-02-28 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0006_alter_labeldata_enddate_alter_labeldata_endpause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldata',
            name='endDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='labeldata',
            name='endPause',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='labeldata',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='labeldata',
            name='startPause',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
