# Generated by Django 5.1.5 on 2025-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_alter_labeldata_enddate_alter_labeldata_endpause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldata',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('en pause', 'En Pause'), ('en conge', 'En Conge'), ('absent', 'Absent'), ('fin de service', 'Fin de Service'), ('anomalie', 'Anomalie'), ('jour ferie', 'Jour Ferie')], max_length=30),
        ),
    ]
