# Generated by Django 4.1.3 on 2023-10-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronerror',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
