# Generated by Django 4.1.3 on 2023-10-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0002_cronerror_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronerror',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
