# Generated by Django 4.1.3 on 2023-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_alter_holiday_created_at_alter_holiday_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
