# Generated by Django 4.1.3 on 2023-06-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_schedule_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='delay',
        ),
        migrations.AddField(
            model_name='overlapperiod',
            name='delay',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
