# Generated by Django 4.1.3 on 2023-06-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_created_at_and_more'),
        ('setting', '0012_overlapperiod_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlapperiod',
            name='departement',
        ),
        migrations.AddField(
            model_name='overlapperiod',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
