# Generated by Django 4.1.3 on 2023-10-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0019_alter_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255, null=True),
        ),
    ]
