# Generated by Django 4.1.3 on 2023-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='additional_hours',
            field=models.TimeField(blank=True, null=True, verbose_name='Heures Supplémentaire'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkin',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivé"),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkin_autorised',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de debut abscence autorisé'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkin_pause',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de pause'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkout',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de départ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkout_autorised',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin abscence autorisé'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkout_pause',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure aprés pause'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duration de travail'),
        ),
    ]
