# Generated by Django 4.1.3 on 2023-05-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_created_at_and_more'),
        ('service', '0003_alter_service_created_at_alter_service_updated_at'),
        ('authentication', '0015_useraccount_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
    ]
