# Generated by Django 4.1.3 on 2023-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_useraccount_departement_useraccount_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
