# Generated by Django 4.1.3 on 2023-07-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_useraccount_gender_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='gender_user',
            field=models.CharField(blank=True, choices=[('homme', 'homme'), ('femme', 'femme')], default='homme', max_length=200, null=True),
        ),
    ]
