# Generated by Django 5.1.5 on 2025-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Jour Férié',
                'verbose_name_plural': 'Jour Fériés',
                'ordering': ['date'],
            },
        ),
    ]
