# Generated by Django 5.1.7 on 2025-04-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jourferie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jourferie',
            name='description',
        ),
    ]
