# Generated by Django 5.1.5 on 2025-02-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0002_alter_employe_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'Arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de Départ')),
                ('pause_debut', models.TimeField(blank=True, null=True, verbose_name='Début de Pause')),
                ('pause_fin', models.TimeField(blank=True, null=True, verbose_name='Fin de Pause')),
                ('status', models.CharField(choices=[('pause', 'Pause'), ('present', 'Présent'), ('conge', 'Congé'), ('absent', 'Absent'), ('fin de service', 'Fin de Service'), ('anomalie', 'Anomalie')], default='present', max_length=20, verbose_name='Statut')),
                ('heures_supplementaires', models.TimeField(blank=True, null=True, verbose_name='Heures Supplémentaires')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='employe.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['date', 'heure_arrivee'],
            },
        ),
    ]
