# Generated by Django 4.1.3 on 2023-04-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktime',
            name='day',
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
