# Generated by Django 4.1.3 on 2023-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_overlapperiod_schedule_configurationdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationdays',
            name='break_duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
