# Generated by Django 4.1.3 on 2023-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_alter_configurationdays_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overlapperiod',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('Holiday schedule', 'Holiday schedule'), ('Fixed schedule', 'Fixed schedule')], max_length=100, null=True),
        ),
    ]
