# Generated by Django 4.1.3 on 2023-06-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_alter_configurationdays_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='delay',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
