# Generated by Django 4.1.3 on 2023-06-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_created_at_and_more'),
        ('setting', '0011_remove_schedule_delay_overlapperiod_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlapperiod',
            name='departement',
            field=models.ManyToManyField(blank=True, null=True, to='department.department'),
        ),
    ]
