# Generated by Django 4.1.3 on 2023-10-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0021_remove_dayschedule_weekday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
