# Generated by Django 4.1.3 on 2023-10-18 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0023_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayschedule',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.day'),
        ),
    ]
