# Generated by Django 4.1.3 on 2022-12-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name="Date d'attendance")),
                ('checkin', models.TimeField(blank=True, default=0, null=True, verbose_name="Heure d'arrivé")),
                ('checkin_pause', models.TimeField(blank=True, default=0, null=True, verbose_name='Heure de pause')),
                ('checkout_pause', models.TimeField(blank=True, default=0, null=True, verbose_name='Heure aprés pause')),
                ('checkout', models.TimeField(blank=True, default=0, null=True, verbose_name='Heure de départ')),
                ('checkin_autorised', models.TimeField(blank=True, default=0, null=True, verbose_name='Heure de debut abscence autorisé')),
                ('checkout_autorised', models.TimeField(blank=True, default=0, null=True, verbose_name='Heure de fin abscence autorisé')),
                ('duration', models.TimeField(blank=True, default=0, null=True, verbose_name='Duration de travail')),
                ('additional_hours', models.TimeField(blank=True, default=0, null=True, verbose_name='Heures Supplémentaire')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
