# Generated by Django 4.1.3 on 2023-05-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Day Off', 'DayOff'), ('Conge', 'Conge'), ('Anomalie', 'Anomalie')], max_length=20, null=True),
        ),
    ]
