# Generated by Django 4.1.3 on 2023-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='type_absence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
