# Generated by Django 4.1.3 on 2023-06-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendance_type_absence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='type_absence',
        ),
    ]
