# Generated by Django 5.1.5 on 2025-02-08 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departement', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricule', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employe', 'Employé')], max_length=20, verbose_name='Rôle')),
                ('date_de_naissance', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('lieu_de_naissance', models.CharField(blank=True, default='', max_length=100, verbose_name='Lieu de Naissance')),
                ('nationalite', models.CharField(blank=True, default='', max_length=100, verbose_name='Nationalité')),
                ('genre_legal', models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10, verbose_name='Genre Légal')),
                ('situation_familiale', models.CharField(choices=[('Celibataire', 'Célibataire'), ('Marie', 'Marié(e)'), ('Divorce', 'Divorcé(e)'), ('Veuf', 'Veuf(ve)')], max_length=20, verbose_name='Situation Familiale')),
                ('CIN', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='CIN')),
                ('num_telephone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Numéro de Téléphone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, default='', max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, default='', max_length=10, verbose_name='Code Postal')),
                ('nom_urgence', models.CharField(max_length=100, verbose_name="Nom du Contact d'Urgence")),
                ('num_telephone_urgence', models.CharField(max_length=20, verbose_name="Numéro de Téléphone d'Urgence")),
                ('compte_bancaire', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Compte Bancaire')),
                ('rib_bancaire', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RIB Bancaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser Status')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='departement.departement', verbose_name='Departement')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='employe_groups', to='auth.group', verbose_name='groups')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='service.service', verbose_name='Service')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='employe_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
