# Generated by Django 5.1.5 on 2025-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['nom'], 'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du Département'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['nom'], name='departement_nom_099f6a_idx'),
        ),
    ]
