# Generated by Django 5.1.5 on 2025-02-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Type de Congé')),
            ],
            options={
                'verbose_name': 'Type de Congé',
                'verbose_name_plural': 'Types de Congé',
            },
        ),
    ]
