# Generated by Django 4.1.3 on 2022-11-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('maladie', 'maladie'), ('maternité', 'maternité'), ('misePied', 'misePied'), ('autorisation', 'autorisation'), ('absenceNonJustifié', 'absenceNonJustifié')], max_length=255)),
                ('title', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name="date début d'absence")),
                ('end_date', models.DateField(blank=True, null=True, verbose_name="date fin d'absence")),
                ('absence_start_time', models.TimeField(blank=True, null=True, verbose_name="Heure debut d'absence")),
                ('absence_end_time', models.TimeField(blank=True, null=True, verbose_name="Heure fin d'absence")),
                ('status', models.CharField(choices=[('Certifiée', 'Certifiée'), ('R', 'Refuse'), ('NonCertifiée', 'NonCertifiée')], max_length=20, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': '-created_at',
                'abstract': False,
            },
        ),
    ]
