# Generated by Django 4.1.3 on 2023-04-11 07:34

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_alter_absence_created_at_alter_absence_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
                ('is_approbation', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': '-created_at',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='absence.absencetype'),
        ),
    ]
