# Generated by Django 4.1.3 on 2023-05-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_absencetype_alter_absence_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='absence.absencetype'),
        ),
    ]
