# Generated by Django 4.1.3 on 2022-12-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.EmailField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': '-created_at',
                'abstract': False,
            },
        ),
    ]
