# Generated by Django 4.1.3 on 2023-03-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_created_at_alter_device_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
