# Generated by Django 5.1.5 on 2025-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='Adresse IP')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('status', models.CharField(choices=[('Connecte', 'Connecté'), ('Non Connecte', 'Non Connecté')], db_index=True, default='Non Connecte', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Appareil',
                'verbose_name_plural': 'Appareils',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('ip', 'port'), name='unique_ip_port')],
            },
        ),
    ]
