# Generated by Django 4.1.3 on 2023-05-08 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conges', '0005_alter_conge_reason_alter_conge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conge',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conges.congetype'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='status',
            field=models.CharField(choices=[('Valider', 'Valider'), ('Refuser', 'Refuser'), ('En_cours', 'En_cours')], default='En_cours', max_length=20),
        ),
    ]
