# Generated by Django 5.1.5 on 2025-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departement', '0002_alter_departement_options_alter_departement_nom_and_more'),
        ('employe', '0002_alter_employe_matricule'),
        ('service', '0002_alter_service_options_alter_service_departement_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['email'], name='employe_emp_email_7254bc_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['CIN'], name='employe_emp_CIN_87a645_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['num_telephone'], name='employe_emp_num_tel_50b041_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['departement'], name='employe_emp_departe_13b4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['service'], name='employe_emp_service_4ba330_idx'),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('CIN',), name='unique_cin'),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('num_telephone',), name='unique_num_telephone'),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('compte_bancaire',), name='unique_compte_bancaire'),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('rib_bancaire',), name='unique_rib_bancaire'),
        ),
    ]
