# Generated by Django 5.1.5 on 2025-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_employe_employe_emp_email_7254bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='uid',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='UID'),
        ),
    ]
