# Generated by Django 5.1.5 on 2025-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_employe_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='CNSS',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='CNSS'),
        ),
        migrations.AddField(
            model_name='employe',
            name='salaire_base',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=15, verbose_name='Salaire de Base'),
            preserve_default=False,
        ),
    ]
