# Generated by Django 5.1.5 on 2025-03-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departement', '0002_alter_departement_options_alter_departement_nom_and_more'),
        ('employe', '0005_employe_cnss_employe_salaire_base'),
        ('service', '0002_alter_service_options_alter_service_departement_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('CNSS',), name='unique_cnss'),
        ),
        migrations.AddConstraint(
            model_name='employe',
            constraint=models.UniqueConstraint(fields=('uid',), name='unique_uid'),
        ),
    ]
