# Generated by Django 5.1.5 on 2025-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0006_employe_unique_cnss_employe_unique_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='zkteco_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ZKTeco User ID'),
        ),
    ]
