# Generated by Django 5.1.5 on 2025-03-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0007_employe_zkteco_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='zkteco_id',
        ),
    ]
