# Generated by Django 5.1.5 on 2025-03-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0008_remove_employe_zkteco_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='password_hash',
            field=models.CharField(default=1, max_length=128, verbose_name='Mot de Passe'),
            preserve_default=False,
        ),
    ]
