# Generated by Django 5.1.5 on 2025-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_employe_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='employe',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Mot de Passe'),
        ),
    ]
