# Generated by Django 5.1.5 on 2025-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0011_alter_employe_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Matricule'),
        ),
    ]
