# Generated by Django 5.1.5 on 2025-05-27 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0012_alter_employe_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='CIN',
            field=models.CharField(db_index=True, max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='CIN'),
        ),
    ]
