# Generated by Django 4.1.3 on 2023-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_attendance_additional_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'get_latest_by': '-created_at', 'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='additional_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heures Supplémentaire'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Duration de travail'),
        ),
    ]
