# Generated by Django 5.1.5 on 2025-02-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employe', '0002_alter_employe_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('raison', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('certifie', models.BooleanField(default=False, verbose_name='Certifié')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='employe.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='absence_abs_date_16e339_idx'), models.Index(fields=['employe'], name='absence_abs_employe_f21e85_idx')],
                'constraints': [models.UniqueConstraint(fields=('employe', 'date'), name='unique_employe_date')],
            },
        ),
    ]
