# Generated by Django 5.1.5 on 2025-02-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'Absence"),
        ),
        migrations.AlterField(
            model_name='absence',
            name='raison',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Raison'),
        ),
    ]
