# Generated by Django 5.1.5 on 2025-02-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_alter_departement_options_alter_departement_nom_and_more'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['nom'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='service',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='departement.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du Service'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['nom'], name='service_ser_nom_3f8cea_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['departement'], name='service_ser_departe_b446d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('nom', 'departement'), name='unique_service_per_departement'),
        ),
    ]
